#!/bin/sh

#  ____              _ _     _   _          
# |  _ \  ___  _ __ ( ) |_  | | | |___  ___ 
# | | | |/ _ \| '_ \|/| __| | | | / __|/ _ \
# | |_| | (_) | | | | | |_  | |_| \__ \  __/
# |____/ \___/|_| |_|  \__|  \___/|___/\___|
                                          


############################################################
# Filename   : hostel-wifi                                 #
# Author     : Abhinesh (--Sad-One)                        #
# Created    : ---                                         #
# To do      : Personal Use                                #
############################################################

curl -s http://www.msftconnecttest.com/redirect | grep -o 'http://10.5.1.1:1000.*"' | sed 's/"//' | xclip -sel clip

# url=$(curl -s http://www.msftconnecttest.com/redirect | grep -o 'http://10.5.1.1:1000.*"')
# echo $url
# echo $url | sed 's/"//' | xclip -sel clip

